version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Packaging Lambda functions...
      - mkdir -p build
      - zip -r build/functionA.zip lambda/functionA/*
      - zip -r build/functionB.zip lambda/functionB/*
artifacts:
  files:
    - build/functionA.zip
    - build/functionB.zip
  discard-paths: yes
